[INT-1304]Add InfluxDb client for store statistic data
landingi/core pull request #17
Opened 2020-11-09 10:50 UTC by Rayn93

InfluxDb client for easy store statistic data in Influx DB. More: https://docs.influxdata.com/influxdb/v1.6/write_protocols/line_protocol_tutorial/

2020-11-09 10:55 UTC, SBielawski requested changes

2020-11-09 10:55 UTC, SBielawski commented on src/Infrastructure/InfluxDB/GuzzleInfluxDbClient.php
> +    public function write(string $measurement, array $tags = [], array $fields = [], $db = 'application'): void
`string $db = 'application'`?

2020-11-09 10:55 UTC, SBielawski commented on src/Infrastructure/InfluxDB/GuzzleInfluxDbClient.php
> +    private function tagsToString(array $tags): string
Możesz użyć `http_build_query` (https://www.php.net/manual/en/function.http-build-query.php)

2020-11-09 10:55 UTC, SBielawski commented on src/Infrastructure/InfluxDB/GuzzleInfluxDbClient.php
> +    private function fieldsToString(array $fields): string
Tak samo tutaj można użyć `http_build_query`

2020-11-09 10:55 UTC, SBielawski commented on src/Infrastructure/InfluxDB/InfluxDbClient.php
> +    public function write(string $measurement, array $tags = [], array $fields = [], $db = 'application'): void;
`string $db = 'application'`

2020-11-09 10:55 UTC, SBielawski commented on src/Infrastructure/InfluxDB/NullInfluxDbClient.php
> +    public function write(string $measurement, array $tags = [], array $fields = [], $db = 'application'): void
`string $db = 'application'`

2020-11-10 08:11 UTC, Rayn93 commented on src/Infrastructure/InfluxDB/GuzzleInfluxDbClient.php
> +    private function tagsToString(array $tags): string
@SBielawski  Tutaj niestety wymagania InfluxDB są na tyle złożone, że http_build_query na dużo nie pomoże. Chyba że ja tej funkcji do koca nie ogarniam.

2020-11-10 10:25 UTC, SBielawski approved these changes

2020-11-10 10:43 UTC, merged